/*
 * Label Studio API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1.11.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type Annotation struct {
	Id int32 `json:"id,omitempty"`
	// Username string
	CreatedUsername string `json:"created_username,omitempty"`
	// Time delta from creation time
	CreatedAgo  string `json:"created_ago,omitempty"`
	CompletedBy int32  `json:"completed_by,omitempty"`
	UniqueId    string `json:"unique_id,omitempty"`
	// The main value of annotator work - labeling result in JSON format
	Result interface{} `json:"result,omitempty"`
	// User skipped the task
	WasCancelled bool `json:"was_cancelled,omitempty"`
	// This annotation is a Ground Truth (ground_truth)
	GroundTruth bool `json:"ground_truth,omitempty"`
	// Creation time
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Last updated time
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Draft creation time
	DraftCreatedAt time.Time `json:"draft_created_at,omitempty"`
	// How much time it took to annotate the task
	LeadTime float32 `json:"lead_time,omitempty"`
	// Original annotation ID that was at the import step or NULL if this annotation wasn't imported
	ImportId int32 `json:"import_id,omitempty"`
	// Action which was performed in the last annotation history item
	LastAction string `json:"last_action,omitempty"`
	// Corresponding task for this annotation
	Task int32 `json:"task,omitempty"`
	// Project ID for this annotation
	Project int32 `json:"project,omitempty"`
	// Last user who updated this annotation
	UpdatedBy int32 `json:"updated_by,omitempty"`
	// Points to the prediction from which this annotation was created
	ParentPrediction int32 `json:"parent_prediction,omitempty"`
	// Points to the parent annotation from which this annotation was created
	ParentAnnotation int32 `json:"parent_annotation,omitempty"`
	// User who created the last annotation history item
	LastCreatedBy int32 `json:"last_created_by,omitempty"`
}
