/*
 * Label Studio API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1.11.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

// JSON dict with parameters
type SerializationOption struct {
	// Include a full json body or IDs only
	OnlyId bool `json:"only_id,omitempty"`
}
