/*
 * Label Studio API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1.11.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type AzureBlobExportStorage struct {
	Id             int32  `json:"id,omitempty"`
	Type_          string `json:"type,omitempty"`
	Synchronizable bool   `json:"synchronizable,omitempty"`
	// Azure blob container
	Container string `json:"container,omitempty"`
	// Azure blob prefix name
	Prefix string `json:"prefix,omitempty"`
	// Cloud storage regex for filtering objects
	RegexFilter string `json:"regex_filter,omitempty"`
	// Interpret objects as BLOBs and generate URLs
	UseBlobUrls bool `json:"use_blob_urls,omitempty"`
	// Azure Blob account name
	AccountName string `json:"account_name,omitempty"`
	// Azure Blob account key
	AccountKey string `json:"account_key,omitempty"`
	// Last sync finished time
	LastSync time.Time `json:"last_sync,omitempty"`
	// Count of tasks synced last time
	LastSyncCount int32 `json:"last_sync_count,omitempty"`
	// Last sync job ID
	LastSyncJob string `json:"last_sync_job,omitempty"`
	Status      string `json:"status,omitempty"`
	// Traceback report for the last failed sync
	Traceback string `json:"traceback,omitempty"`
	// Meta and debug information about storage processes
	Meta interface{} `json:"meta,omitempty"`
	// Cloud storage title
	Title string `json:"title,omitempty"`
	// Cloud storage description
	Description string `json:"description,omitempty"`
	// Creation time
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Deletion from storage enabled
	CanDeleteObjects bool `json:"can_delete_objects,omitempty"`
	// A unique integer value identifying this project.
	Project int32 `json:"project"`
}
