/*
 * Label Studio API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1.11.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type TaskFilterOptions struct {
	// Apply filters from the view ID (a tab from the Data Manager)
	View int32 `json:"view,omitempty"`
	// `only` - include all tasks with skipped annotations<br>`exclude` - exclude all tasks with skipped annotations
	Skipped string `json:"skipped,omitempty"`
	// `only` - include all finished tasks (is_labeled = true)<br>`exclude` - exclude all finished tasks
	Finished string `json:"finished,omitempty"`
	// `only` - include all tasks with at least one not skipped annotation<br>`exclude` - exclude all tasks with at least one not skipped annotation
	Annotated           string `json:"annotated,omitempty"`
	OnlyWithAnnotations bool   `json:"only_with_annotations,omitempty"`
}
