/*
 * Label Studio API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1.11.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type S3ImportStorage struct {
	Id             int32  `json:"id,omitempty"`
	Type_          string `json:"type,omitempty"`
	Synchronizable bool   `json:"synchronizable,omitempty"`
	Presign        bool   `json:"presign,omitempty"`
	// Last sync finished time
	LastSync time.Time `json:"last_sync,omitempty"`
	// Count of tasks synced last time
	LastSyncCount int32 `json:"last_sync_count,omitempty"`
	// Last sync job ID
	LastSyncJob string `json:"last_sync_job,omitempty"`
	Status      string `json:"status,omitempty"`
	// Traceback report for the last failed sync
	Traceback string `json:"traceback,omitempty"`
	// Meta and debug information about storage processes
	Meta interface{} `json:"meta,omitempty"`
	// Cloud storage title
	Title string `json:"title,omitempty"`
	// Cloud storage description
	Description string `json:"description,omitempty"`
	// Creation time
	CreatedAt time.Time `json:"created_at,omitempty"`
	// S3 bucket name
	Bucket string `json:"bucket,omitempty"`
	// S3 bucket prefix
	Prefix string `json:"prefix,omitempty"`
	// Cloud storage regex for filtering objects
	RegexFilter string `json:"regex_filter,omitempty"`
	// Interpret objects as BLOBs and generate URLs
	UseBlobUrls bool `json:"use_blob_urls,omitempty"`
	// AWS_ACCESS_KEY_ID
	AwsAccessKeyId string `json:"aws_access_key_id,omitempty"`
	// AWS_SECRET_ACCESS_KEY
	AwsSecretAccessKey string `json:"aws_secret_access_key,omitempty"`
	// AWS_SESSION_TOKEN
	AwsSessionToken string `json:"aws_session_token,omitempty"`
	// AWS SSE KMS Key ID
	AwsSseKmsKeyId string `json:"aws_sse_kms_key_id,omitempty"`
	// AWS Region
	RegionName string `json:"region_name,omitempty"`
	// S3 Endpoint
	S3Endpoint string `json:"s3_endpoint,omitempty"`
	// Presigned URLs TTL (in minutes)
	PresignTtl int32 `json:"presign_ttl,omitempty"`
	// Perform recursive scan over the bucket content
	RecursiveScan bool `json:"recursive_scan,omitempty"`
	// A unique integer value identifying this project.
	Project int32 `json:"project"`
}
