/*
 * Label Studio API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1.11.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type GcsImportStorage struct {
	Id             int32  `json:"id,omitempty"`
	Type_          string `json:"type,omitempty"`
	Synchronizable bool   `json:"synchronizable,omitempty"`
	Presign        bool   `json:"presign,omitempty"`
	// GCS bucket name
	Bucket string `json:"bucket,omitempty"`
	// GCS bucket prefix
	Prefix string `json:"prefix,omitempty"`
	// Cloud storage regex for filtering objects
	RegexFilter string `json:"regex_filter,omitempty"`
	// Interpret objects as BLOBs and generate URLs
	UseBlobUrls bool `json:"use_blob_urls,omitempty"`
	// The content of GOOGLE_APPLICATION_CREDENTIALS json file
	GoogleApplicationCredentials string `json:"google_application_credentials,omitempty"`
	// Google project ID
	GoogleProjectId string `json:"google_project_id,omitempty"`
	// Last sync finished time
	LastSync time.Time `json:"last_sync,omitempty"`
	// Count of tasks synced last time
	LastSyncCount int32 `json:"last_sync_count,omitempty"`
	// Last sync job ID
	LastSyncJob string `json:"last_sync_job,omitempty"`
	Status      string `json:"status,omitempty"`
	// Traceback report for the last failed sync
	Traceback string `json:"traceback,omitempty"`
	// Meta and debug information about storage processes
	Meta interface{} `json:"meta,omitempty"`
	// Cloud storage title
	Title string `json:"title,omitempty"`
	// Cloud storage description
	Description string `json:"description,omitempty"`
	// Creation time
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Presigned URLs TTL (in minutes)
	PresignTtl int32 `json:"presign_ttl,omitempty"`
	// A unique integer value identifying this project.
	Project int32 `json:"project"`
}
