/*
 * Label Studio API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1.11.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type Webhook struct {
	Id           int32 `json:"id,omitempty"`
	Organization int32 `json:"organization,omitempty"`
	Project      int32 `json:"project,omitempty"`
	// URL of webhook
	Url string `json:"url"`
	// If value is False send only action
	SendPayload bool `json:"send_payload,omitempty"`
	// If value is False - used only for actions from WebhookAction
	SendForAllActions bool `json:"send_for_all_actions,omitempty"`
	// Key Value Json of headers
	Headers interface{} `json:"headers,omitempty"`
	// If value is False the webhook is disabled
	IsActive bool     `json:"is_active,omitempty"`
	Actions  []string `json:"actions,omitempty"`
	// Creation time
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Last update time
	UpdatedAt time.Time `json:"updated_at,omitempty"`
}
