/*
 * Label Studio API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1.11.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type Export struct {
	Title     string      `json:"title,omitempty"`
	Id        int32       `json:"id,omitempty"`
	CreatedBy *UserSimple `json:"created_by,omitempty"`
	// Creation time
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Complete or fail time
	FinishedAt       time.Time         `json:"finished_at,omitempty"`
	Status           string            `json:"status,omitempty"`
	Md5              string            `json:"md5,omitempty"`
	Counters         interface{}       `json:"counters,omitempty"`
	ConvertedFormats []ConvertedFormat `json:"converted_formats,omitempty"`
}
