/*
 * Label Studio API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1.11.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type UserSerializerWithProjects struct {
	Id                 int32     `json:"id,omitempty"`
	FirstName          string    `json:"first_name,omitempty"`
	LastName           string    `json:"last_name,omitempty"`
	Username           string    `json:"username"`
	Email              string    `json:"email,omitempty"`
	LastActivity       time.Time `json:"last_activity,omitempty"`
	Avatar             string    `json:"avatar,omitempty"`
	Initials           string    `json:"initials,omitempty"`
	Phone              string    `json:"phone,omitempty"`
	ActiveOrganization int32     `json:"active_organization,omitempty"`
	// Allow sending newsletters to user
	AllowNewsletters      bool   `json:"allow_newsletters,omitempty"`
	CreatedProjects       string `json:"created_projects,omitempty"`
	ContributedToProjects string `json:"contributed_to_projects,omitempty"`
}
