/*
 * Label Studio API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1.11.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type Organization struct {
	Id          int32     `json:"id,omitempty"`
	Title       string    `json:"title"`
	Token       string    `json:"token,omitempty"`
	CreatedAt   time.Time `json:"created_at,omitempty"`
	UpdatedAt   time.Time `json:"updated_at,omitempty"`
	ContactInfo string    `json:"contact_info,omitempty"`
	CreatedBy   int32     `json:"created_by,omitempty"`
	Users       []int32   `json:"users,omitempty"`
}
