/*
 * Label Studio API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1.11.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type Label struct {
	Id    int32   `json:"id,omitempty"`
	Links []int32 `json:"links,omitempty"`
	// Time of label creation
	CreatedAt time.Time `json:"created_at,omitempty"`
	// Time of label modification
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// Label value
	Value interface{} `json:"value"`
	// Label title
	Title string `json:"title"`
	// Label description
	Description string `json:"description,omitempty"`
	// Status of label
	Approved bool `json:"approved,omitempty"`
	// User who made this label
	CreatedBy int32 `json:"created_by"`
	// User who approved this label
	ApprovedBy   int32   `json:"approved_by,omitempty"`
	Organization int32   `json:"organization"`
	Projects     []int32 `json:"projects,omitempty"`
}
