/*
 * Label Studio API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1.11.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

type Filter struct {
	Id int32 `json:"id,omitempty"`
	// To keep filter order
	Index int32 `json:"index,omitempty"`
	// Field name
	Column string `json:"column"`
	// Field type
	Type_ string `json:"type"`
	// Filter operator
	Operator string `json:"operator"`
	// Filter value
	Value interface{} `json:"value,omitempty"`
}
