/*
 * Label Studio API
 *
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * API version: v1.11.0
 * Generated by: Swagger Codegen (https://github.com/swagger-api/swagger-codegen.git)
 */

package swagger

import (
	"time"
)

type MlBackend struct {
	Id    int32  `json:"id,omitempty"`
	State string `json:"state,omitempty"`
	// Used to interactively annotate tasks. If true, model returns one list with results
	IsInteractive bool `json:"is_interactive,omitempty"`
	// URL for the machine learning model server
	Url string `json:"url"`
	// Error message in error state
	ErrorMessage string `json:"error_message,omitempty"`
	// Name of the machine learning backend
	Title string `json:"title,omitempty"`
	// Description for the machine learning backend
	Description string `json:"description,omitempty"`
	// Current model version associated with this machine learning backend
	ModelVersion string `json:"model_version,omitempty"`
	// Response model timeout
	Timeout   float32   `json:"timeout,omitempty"`
	CreatedAt time.Time `json:"created_at,omitempty"`
	UpdatedAt time.Time `json:"updated_at,omitempty"`
	// If false, model version is set by the user, if true - getting latest version from backend.
	AutoUpdate bool  `json:"auto_update,omitempty"`
	Project    int32 `json:"project"`
}
